{
 "title": "Kubernetes Event Dashboard Copy",
 "description": "Kubernetes Event Dashboard",
 "tags": [ "loki" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "loki" },
   { "name": "namespace", "query": "label_values(namespace)" },
   { "name": "contains", "label": "Search events" }
  ]
 },
 "panels": [
  { "title": "Kubernetes Events - Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Image Pull Failed",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({sourcing=\"kubernetes-event\"} |= `Error: ImagePullBackOff` | json | __error__=`` | metadata_namespace=~`$namespace` | reason=`Failed` | line_format `{{ .message }}` [$__interval]))"
    }
   ]
  },
  {
   "title": "Liveness Probe Failed",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({sourcing=\"kubernetes-event\"} |= `failed liveness probe` | json | __error__=`` | metadata_namespace=~`$namespace` | reason=`Killing` [$__interval]))"
    }
   ]
  },
  {
   "title": "Readness Probe Failed",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({sourcing=\"kubernetes-event\"} |= `Readiness probe failed` | json | __error__=`` | metadata_namespace=~`$namespace` | reason=`Unhealthy` [$__interval]))"
    }
   ]
  },
  {
   "title": "Scheduling Failed",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({sourcing=\"kubernetes-event\"} | json | __error__=`` | metadata_namespace=~`$namespace` | reason=`FailedScheduling` [$__interval]))"
    }
   ]
  },
  {
   "title": "Pod Evicted",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({sourcing=\"kubernetes-event\"} |= \"Marking for deletion Pod\" | json | __error__=`` | metadata_namespace=~`$namespace` | reason=\"TaintManagerEviction\" [$__interval]))"
    }
   ]
  },
  {
   "title": "Container OOM Killed",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({sourcing=\"kubernetes-event\"} | json | __error__=`` | metadata_namespace=~`$namespace` | reason=`OOMKilling` [$__interval]))"
    }
   ]
  },
  {
   "title": "Warnings",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(count_over_time({sourcing=\"kubernetes-event\"} | json | __error__=`` | metadata_namespace=~`$namespace` | type=`Warning` [$__interval]))",
     "legendFormat": "Warning"
    }
   ]
  },
  {
   "title": "System Rebooted",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({sourcing=\"kubernetes-event\"} | json | __error__=`` | reason=`Rebooted` [$__interval]))"
    }
   ]
  },
  {
   "title": "Resource Purged Successes",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({sourcing=\"kubernetes-event\"} | json | __error__=`` | metadata_namespace=~`$namespace` | reason=`SuccessfulDelete` [$__interval]))"
    }
   ]
  },
  {
   "title": "Container Crashed",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({sourcing=\"kubernetes-event\"} | json | __error__=`` | metadata_namespace=~`$namespace` | reason=`BackOff` [$__interval]))"
    }
   ]
  },
  {
   "title": "Pod Evicted",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({sourcing=\"kubernetes-event\"} |= `Marking for deletion Pod` | json | __error__=`` | metadata_namespace=~`$namespace` | reason=`TaintManagerEviction` [$__range]))"
    }
   ]
  },
  {
   "title": "Volume Mount Failed",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({sourcing=\"kubernetes-event\"} | json | __error__=`` | metadata_namespace=~`$namespace` | reason=`FailedMount` [$__interval]))"
    }
   ]
  },
  {
   "title": "Allocation Failed",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({sourcing=\"kubernetes-event\"} | json | __error__=`` | metadata_namespace=~`$namespace` | reason=`AllocationFailed` [$__interval]))"
    }
   ]
  },
  {
   "title": "Overview",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "sum by (type) (count_over_time({sourcing=\"kubernetes-event\"} | json | __error__=`` | metadata_namespace=~`$namespace` [$__interval]))",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Kubernetes Top 10 Event",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "expr": "topk(10, sum by(reason) (count_over_time({sourcing=\"kubernetes-event\"} | json | __error__=`` | metadata_namespace=~`$namespace` [$__interval])))",
     "legendFormat": "{{reason}}"
    }
   ]
  },
  {
   "title": "Kubernetes Events - Distribution",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 }
  },
  {
   "title": "Events by Reason",
   "type": "piechart",
   "gridPos": { "h": 14, "w": 6, "x": 0, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by(reason) (count_over_time({sourcing=\"kubernetes-event\"} | json | __error__=`` | metadata_namespace=~`$namespace` [$__interval]))",
     "legendFormat": "{{reason}}"
    }
   ]
  },
  {
   "title": "Events by Namespace",
   "type": "piechart",
   "gridPos": { "h": 14, "w": 6, "x": 6, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by(metadata_namespace) (count_over_time({sourcing=\"kubernetes-event\"} | json | __error__=`` | metadata_namespace=~`$namespace` [$__interval]))",
     "legendFormat": "{{metadata_namespace}}"
    }
   ]
  },
  {
   "title": "Events by Source",
   "type": "piechart",
   "gridPos": { "h": 14, "w": 6, "x": 12, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by(source_component) (count_over_time({sourcing=\"kubernetes-event\"} | json | __error__=`` | metadata_namespace=~`$namespace` [$__interval]))",
     "legendFormat": "{{source_component}}"
    }
   ]
  },
  {
   "title": "Events by Kind",
   "type": "piechart",
   "gridPos": { "h": 14, "w": 6, "x": 18, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by(involvedObject_kind) (count_over_time({sourcing=\"kubernetes-event\"} | json | __error__=`` | metadata_namespace=~`$namespace` [$__interval]))",
     "legendFormat": "{{involvedObject_kind}}"
    }
   ]
  },
  { "title": "Kubernetes Events - Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Events Details",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 37 },
   "targets": [
    {
     "expr": "{sourcing=\"kubernetes-event\"} |~ `(?i)$contains` | json | __error__=`` | metadata_namespace=~`$namespace`"
    }
   ]
  },
  { "title": "Kubernetes Events - Raw Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "type": "logs",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 51 },
   "targets": [
    {
     "expr": "{sourcing=\"kubernetes-event\"} |~ `(?i)$contains` | json | __error__=`` | metadata_namespace=~`$namespace`"
    }
   ]
  }
 ]
}