{
 "title": "Openstack Dashboard",
 "description": "This dashboard visualizes data exporter by the Prometheus OpenStack Exporter",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cloud",
    "query": "openstack_exporter_cache_age_seconds"
   },
   {
    "name": "instance",
    "query": "openstack_exporter_cache_refresh_duration_seconds{cloud=\"$cloud\"}"
   },
   {
    "name": "swifthost",
    "query": "swift_disk_usage_bytes{type=\"used\",cloud=\"$cloud\"}"
   },
   {
    "name": "neutron_net",
    "label": "External networks",
    "query": "neutron_public_ip_usage{cloud=\"$cloud\",ip_type=\"routerip\"}"
   },
   {
    "name": "hypervisor",
    "query": "hypervisor_vcpus_total{cloud=\"$cloud\"}"
   },
   {
    "name": "hypervisor_status",
    "query": "hypervisor_vcpus_total{cloud=\"$cloud\",hypervisor_hostname=\"$hypervisor\"}"
   },
   {
    "name": "aggregate",
    "label": "availability zone",
    "query": "hypervisor_vcpus_total{cloud=\"$cloud\"}"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "content": "# Openstack dashboard: $cloud\n\n* openstack data is cached for 5 minutes by default\n* \"Free IPs\" are not owned by any tenant and available for allocation\n* \"Unused IPs\" are owned by a tenant but not currently associated with an instance"
  },
  {
   "title": "Free IPs (ext_net)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(neutron_net_size{network_name=\"ext_net\",cloud=\"$cloud\"}) - sum(neutron_public_ip_usage{subnet_name=\"ext_net\",cloud=\"$cloud\"})"
    }
   ]
  },
  {
   "title": "Unused IPs (ext_net)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(neutron_net_size{network_name=\"ext_net\",cloud=\"$cloud\"}) - sum(neutron_public_ip_usage{subnet_name=\"ext_net\",cloud=\"$cloud\",ip_status=\"ACTIVE\"})) - (sum(neutron_net_size{network_name=\"ext_net\",cloud=\"$cloud\"}) - sum(neutron_public_ip_usage{subnet_name=\"ext_net\",cloud=\"$cloud\"}))"
    }
   ]
  },
  {
   "title": "Schedulable cpu2-ram4-disk20 instances",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(hypervisor_schedulable_instances{nova_service_status=\"enabled\",cloud=\"$cloud\"})"
    }
   ]
  },
  {
   "title": "Free swift space - raw",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 3 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(swift_disk_usage_bytes{type=\"size\",cloud=\"$cloud\"}) - sum(swift_disk_usage_bytes{type=\"used\",cloud=\"$cloud\"})"
    }
   ]
  },
  {
   "title": "Free swift space -usable (rf=3)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 3 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(swift_disk_usage_bytes{type=\"size\",cloud=\"$cloud\"}) - sum(swift_disk_usage_bytes{type=\"used\",cloud=\"$cloud\"})) /3"
    }
   ]
  },
  {
   "title": "KPI graphs - 14 days",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Swift - usable free space",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "(sum(swift_disk_usage_bytes{type=\"size\",cloud=\"$cloud\"}) - sum(swift_disk_usage_bytes{type=\"used\",cloud=\"$cloud\"}))/3",
       "legendFormat": "Free usable space"
      }
     ]
    },
    {
     "title": "Schedulable cpu2-ram4-disk20 instances",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(hypervisor_schedulable_instances{cloud=\"$cloud\",nova_service_status=\"enabled\"}) by (aggregate)",
       "legendFormat": "{{aggregate}}"
      }
     ]
    },
    {
     "title": "Free production floating IPs",
     "type": "graph",
     "gridPos": { "h": 7, "w": 10, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(neutron_net_size{network_name=\"ext_net\",cloud=\"$cloud\"}) - sum(neutron_public_ip_usage{subnet_name=\"ext_net\",cloud=\"$cloud\"})"
      }
     ]
    },
    {
     "title": "Time until swift full (based on last 14 days)",
     "type": "singlestat",
     "gridPos": { "h": 7, "w": 4, "x": 10, "y": 14 },
     "format": "s",
     "valueName": "current",
     "targets": [
      {
       "expr": "((swift_disk_usage_bytes:sum:by_cloud_type{type=\"size\",cloud=\"$cloud\"} - on(cloud) swift_disk_usage_bytes:sum:by_cloud_type{type=\"used\",cloud=\"$cloud\"}) / on () deriv(swift_disk_usage_bytes:sum:by_cloud_type{type=\"used\",cloud=\"$cloud\"}[14d])) >0"
      }
     ]
    },
    {
     "title": "Time until compute full",
     "type": "singlestat",
     "gridPos": { "h": 7, "w": 4, "x": 14, "y": 14 },
     "format": "s",
     "valueName": "current",
     "targets": [
      {
       "expr": "hypervisor_schedulable_instances:sum:by_cloud_status{cloud=\"$cloud\",nova_service_status=\"enabled\"} / -deriv(hypervisor_schedulable_instances:sum:by_cloud_status{cloud=\"$cloud\",nova_service_status=\"enabled\"}[14d]) >0"
      }
     ]
    },
    {
     "title": "Top compute with cpu2-ram4-disk20 space",
     "type": "table",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 14 },
     "targets": [
      {
       "expr": "topk(5,hypervisor_schedulable_instances{cloud=\"$cloud\",aggregate=~\"$aggregate\",nova_service_status=\"enabled\"})",
       "legendFormat": "{{hypervisor_hostname}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Neutron",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "IPs in $neutron_net",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
     "repeat": "neutron_net",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(neutron_public_ip_usage{subnet_name=\"$neutron_net\",ip_type=\"floatingip\",cloud=\"$cloud\"})",
       "legendFormat": "Floating IPs"
      },
      {
       "expr": "sum(neutron_public_ip_usage{subnet_name=\"$neutron_net\",ip_type=\"routerip\",cloud=\"$cloud\"})",
       "legendFormat": "Router IPs"
      },
      {
       "expr": "sum(neutron_net_size{network_name=\"$neutron_net\",cloud=\"$cloud\"}) - sum(neutron_public_ip_usage{subnet_name=\"$neutron_net\",cloud=\"$cloud\"})",
       "legendFormat": "Free"
      }
     ]
    },
    {
     "title": "IPs in $neutron_net",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(neutron_public_ip_usage{subnet_name=\"$neutron_net\",ip_type=\"floatingip\",cloud=\"$cloud\"})",
       "legendFormat": "Floating IPs"
      },
      {
       "expr": "sum(neutron_public_ip_usage{subnet_name=\"$neutron_net\",ip_type=\"routerip\",cloud=\"$cloud\"})",
       "legendFormat": "Router IPs"
      },
      {
       "expr": "sum(neutron_net_size{network_name=\"$neutron_net\",cloud=\"$cloud\"}) - sum(neutron_public_ip_usage{subnet_name=\"$neutron_net\",cloud=\"$cloud\"})",
       "legendFormat": "Free"
      }
     ]
    },
    {
     "title": "IPs in $neutron_net",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(neutron_public_ip_usage{subnet_name=\"$neutron_net\",ip_type=\"floatingip\",cloud=\"$cloud\"})",
       "legendFormat": "Floating IPs"
      },
      {
       "expr": "sum(neutron_public_ip_usage{subnet_name=\"$neutron_net\",ip_type=\"routerip\",cloud=\"$cloud\"})",
       "legendFormat": "Router IPs"
      },
      {
       "expr": "sum(neutron_net_size{network_name=\"$neutron_net\",cloud=\"$cloud\"}) - sum(neutron_public_ip_usage{subnet_name=\"$neutron_net\",cloud=\"$cloud\"})",
       "legendFormat": "Free"
      }
     ]
    },
    {
     "title": "Tenants with unused IPs in $neutron_net",
     "type": "table",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 15 },
     "repeat": "neutron_net",
     "targets": [
      {
       "expr": "neutron_public_ip_usage{subnet_name=\"$neutron_net\",ip_type=\"floatingip\", ip_status=\"DOWN\",tenant=~\".+\",cloud=\"$cloud\"}",
       "legendFormat": "{{tenant}}"
      }
     ]
    },
    {
     "title": "Tenants with unused IPs in $neutron_net",
     "type": "table",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 15 },
     "targets": [
      {
       "expr": "neutron_public_ip_usage{subnet_name=\"$neutron_net\",ip_type=\"floatingip\", ip_status=\"DOWN\",tenant=~\".+\",cloud=\"$cloud\"}",
       "legendFormat": "{{tenant}}"
      }
     ]
    },
    {
     "title": "Tenants with unused IPs in $neutron_net",
     "type": "table",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 15 },
     "targets": [
      {
       "expr": "neutron_public_ip_usage{subnet_name=\"$neutron_net\",ip_type=\"floatingip\", ip_status=\"DOWN\",tenant=~\".+\",cloud=\"$cloud\"}",
       "legendFormat": "{{tenant}}"
      }
     ]
    },
    {
     "title": "Tenants using most IPs in $neutron_net",
     "type": "table",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 22 },
     "repeat": "neutron_net",
     "targets": [
      {
       "expr": "topk(10, neutron_public_ip_usage{subnet_name=\"$neutron_net\",ip_type=\"floatingip\",tenant=~\".+\",cloud=\"$cloud\"})",
       "legendFormat": "{{tenant}}"
      }
     ]
    },
    {
     "title": "Tenants using most IPs in $neutron_net",
     "type": "table",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 22 },
     "targets": [
      {
       "expr": "topk(10, neutron_public_ip_usage{subnet_name=\"$neutron_net\",ip_type=\"floatingip\",tenant=~\".+\",cloud=\"$cloud\"})",
       "legendFormat": "{{tenant}}"
      }
     ]
    },
    {
     "title": "Tenants using most IPs in $neutron_net",
     "type": "table",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 22 },
     "targets": [
      {
       "expr": "topk(10, neutron_public_ip_usage{subnet_name=\"$neutron_net\",ip_type=\"floatingip\",tenant=~\".+\",cloud=\"$cloud\"})",
       "legendFormat": "{{tenant}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Compute",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Free memory",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 9 },
     "format": "mbytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "(sum(hypervisor_memory_mbs_total{cloud=\"$cloud\"}) * sum(openstack_allocation_ratio{cloud=\"$cloud\",resource=\"ram\"}) - sum(hypervisor_memory_mbs_used{cloud=\"$cloud\",nova_service_status=\"enabled\"}))"
      }
     ]
    },
    {
     "title": "Free vCPUs",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 4, "y": 9 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(hypervisor_vcpus_total{cloud=\"$cloud\",nova_service_status=\"enabled\"})*sum(openstack_allocation_ratio{cloud=\"$cloud\",resource=\"vcpu\"}) - sum(hypervisor_vcpus_used{cloud=\"$cloud\",nova_service_status=\"enabled\"})"
      }
     ]
    },
    {
     "title": "Free disk",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 8, "y": 9 },
     "format": "gbytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(hypervisor_disk_gbs_total{cloud=\"$cloud\",nova_service_status=\"enabled\"}) * sum(openstack_allocation_ratio{cloud=\"$cloud\",resource=\"disk\"}) - sum(hypervisor_disk_gbs_used{cloud=\"$cloud\",nova_service_status=\"enabled\"})"
      }
     ]
    },
    {
     "title": "CPU Overcommit ratio",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 12, "y": 9 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "openstack_allocation_ratio{cloud=\"$cloud\",resource=\"vcpu\"}",
       "legendFormat": "Openstack CPU allocation ratio"
      }
     ]
    },
    {
     "title": "RAM Overcommit ratio",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 16, "y": 9 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "openstack_allocation_ratio{cloud=\"$cloud\",resource=\"ram\"}",
       "legendFormat": "RAM allocation ratio"
      }
     ]
    },
    {
     "title": "Disk Overcommit ratio",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 20, "y": 9 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "openstack_allocation_ratio{cloud=\"$cloud\",resource=\"disk\"}",
       "legendFormat": "Disk Overcommit ratio"
      }
     ]
    },
    {
     "title": "Schedulable cpu2-ram4-disk20 instances ($aggregate)",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 12 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(hypervisor_schedulable_instances{nova_service_status=\"enabled\",cloud=\"$cloud\",aggregate=~\"$aggregate\"})",
       "legendFormat": "Schedulable instances"
      }
     ]
    },
    {
     "title": "Schedulable cpu2-ram4-disk20 instances",
     "type": "graph",
     "gridPos": { "h": 5, "w": 20, "x": 4, "y": 12 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(hypervisor_schedulable_instances{cloud=\"$cloud\",nova_service_status=\"enabled\"}) by (aggregate)",
       "legendFormat": "{{aggregate}}"
      }
     ]
    },
    {
     "title": "Free vCPUs",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(sum(hypervisor_vcpus_total{aggregate=~\".+\",cloud=\"$cloud\",nova_service_status=\"enabled\"} * on(cloud) group_left openstack_allocation_ratio{cloud=\"$cloud\",resource=\"vcpu\"}) by(aggregate)) - (sum(hypervisor_vcpus_used{aggregate=~\".+\",cloud=\"$cloud\",nova_service_status=\"enabled\"}) by(aggregate))",
       "legendFormat": "{{aggregate}}"
      }
     ]
    },
    {
     "title": "Free Disk",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 17 },
     "yaxes": [
      { "format": "gbytes" }
     ],
     "targets": [
      {
       "expr": "(sum(hypervisor_disk_gbs_total{aggregate=~\".+\",cloud=\"$cloud\",nova_service_status=\"enabled\"} * on(cloud) group_left openstack_allocation_ratio{cloud=\"$cloud\",resource=\"disk\"}) by(aggregate)) - (sum(hypervisor_disk_gbs_used{aggregate=~\".+\",cloud=\"$cloud\",nova_service_status=\"enabled\"}) by(aggregate))",
       "legendFormat": "{{aggregate}}"
      }
     ]
    },
    {
     "title": "Free memory",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "mbytes" }
     ],
     "targets": [
      {
       "expr": "(sum(hypervisor_memory_mbs_total{aggregate=~\".+\",cloud=\"$cloud\",nova_service_status=\"enabled\"} * on(cloud) group_left openstack_allocation_ratio{cloud=\"$cloud\",resource=\"ram\"}) by(aggregate)) - (sum(hypervisor_memory_mbs_used{aggregate=~\".+\",cloud=\"$cloud\",nova_service_status=\"enabled\"}) by(aggregate))",
       "legendFormat": "{{aggregate}}"
      }
     ]
    },
    {
     "title": "Running VMs",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 22 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(hypervisor_running_vms{aggregate=~\".+\",cloud=\"$cloud\"}) by (aggregate)",
       "legendFormat": "{{aggregate}}"
      }
     ]
    },
    {
     "title": "Schedulable cpu2-ram4-disk20 instances ($aggregate)",
     "type": "table",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 27 },
     "targets": [
      {
       "expr": "hypervisor_schedulable_instances{cloud=\"$cloud\",aggregate=~\"$aggregate\"}",
       "legendFormat": "{{hypervisor_hostname}} ({{nova_service_status}})"
      },
      {}
     ]
    },
    {
     "title": "Free vCPU per host ($aggregate)",
     "type": "table",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 27 },
     "targets": [
      {
       "expr": "(hypervisor_vcpus_total{cloud=\"$cloud\",aggregate=~\"$aggregate\"} * on(cloud) group_left openstack_allocation_ratio{cloud=\"$cloud\",resource=\"vcpu\"}) - on(cloud,hypervisor_hostname,nova_service_status) hypervisor_vcpus_used{cloud=\"$cloud\",aggregate=~\"$aggregate\"}",
       "legendFormat": "{{hypervisor_hostname}} ({{nova_service_status}})"
      }
     ]
    },
    {
     "title": "Free RAM GBs per host ($aggregate)",
     "type": "table",
     "gridPos": { "h": 9, "w": 6, "x": 12, "y": 27 },
     "targets": [
      {
       "expr": "((hypervisor_memory_mbs_total{cloud=\"$cloud\",aggregate=~\"$aggregate\"} * on(cloud) group_left openstack_allocation_ratio{cloud=\"$cloud\",resource=\"ram\"}) - on(cloud,hypervisor_hostname,nova_service_status) hypervisor_memory_mbs_used{cloud=\"$cloud\",aggregate=~\"$aggregate\"}) / 1024",
       "legendFormat": "{{hypervisor_hostname}} ({{nova_service_status}})"
      }
     ]
    },
    {
     "title": "Free disk GBs per host ($aggregate)",
     "type": "table",
     "gridPos": { "h": 9, "w": 6, "x": 18, "y": 27 },
     "targets": [
      {
       "expr": "(hypervisor_disk_gbs_total{cloud=\"$cloud\",aggregate=~\"$aggregate\"} * on(cloud) group_left openstack_allocation_ratio{cloud=\"$cloud\",resource=\"disk\"}) - on(cloud,hypervisor_hostname,nova_service_status) hypervisor_disk_gbs_used{cloud=\"$cloud\",aggregate=~\"$aggregate\"}",
       "legendFormat": "{{hypervisor_hostname}} ({{nova_service_status}})"
      }
     ]
    }
   ]
  },
  {
   "title": "Swift",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Swift disk space",
     "type": "graph",
     "gridPos": { "h": 7, "w": 14, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(swift_disk_usage_bytes{type=\"used\",cloud=\"$cloud\"}) by (hostname)",
       "legendFormat": "{{hostname}}"
      },
      {
       "expr": "sum(swift_disk_usage_bytes{type=\"size\",cloud=\"$cloud\"}) - sum(swift_disk_usage_bytes{type=\"used\",cloud=\"$cloud\"})",
       "legendFormat": "Free"
      }
     ]
    },
    {
     "title": "Free space (raw)",
     "type": "singlestat",
     "gridPos": { "h": 7, "w": 4, "x": 14, "y": 10 },
     "format": "bytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(swift_disk_usage_bytes{type=\"size\",cloud=\"$cloud\"}) - sum(swift_disk_usage_bytes{type=\"used\",cloud=\"$cloud\"})"
      }
     ]
    },
    {
     "title": "Disk with least space free",
     "type": "table",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 10 },
     "targets": [
      {
       "expr": "bottomk(10, sum(swift_disk_usage_bytes{type=\"size\",cloud=\"$cloud\"}) by (hostname, device) - sum(swift_disk_usage_bytes{type=\"used\",cloud=\"$cloud\"}) by (hostname, device))",
       "legendFormat": "{{hostname}} {{device}}"
      }
     ]
    },
    {
     "title": "Object replication duration",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "swift_replication_duration_seconds{ring=\"object\",cloud=\"$cloud\"}",
       "legendFormat": "{{hostname}}"
      }
     ]
    },
    {
     "title": "Container replication duration",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 17 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "swift_replication_duration_seconds{ring=\"container\",cloud=\"$cloud\"}",
       "legendFormat": "{{hostname}}"
      }
     ]
    },
    {
     "title": "Account replication duration",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 17 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "swift_replication_duration_seconds{ring=\"account\",cloud=\"$cloud\"}",
       "legendFormat": "{{hostname}}"
      }
     ]
    },
    {
     "title": "$swifthost container replication",
     "type": "graph",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 24 },
     "repeat": "swifthost",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "swift_replication_stats{hostname=~\"$swifthost\", ring=\"container\", cloud=\"$cloud\"}",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "$swifthost container replication",
     "type": "graph",
     "gridPos": { "h": 7, "w": 4, "x": 4, "y": 24 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "swift_replication_stats{hostname=~\"$swifthost\", ring=\"container\", cloud=\"$cloud\"}",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "$swifthost container replication",
     "type": "graph",
     "gridPos": { "h": 7, "w": 4, "x": 8, "y": 24 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "swift_replication_stats{hostname=~\"$swifthost\", ring=\"container\", cloud=\"$cloud\"}",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "$swifthost container replication",
     "type": "graph",
     "gridPos": { "h": 7, "w": 4, "x": 12, "y": 24 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "swift_replication_stats{hostname=~\"$swifthost\", ring=\"container\", cloud=\"$cloud\"}",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "$swifthost container replication",
     "type": "graph",
     "gridPos": { "h": 7, "w": 4, "x": 16, "y": 24 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "swift_replication_stats{hostname=~\"$swifthost\", ring=\"container\", cloud=\"$cloud\"}",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "$swifthost container replication",
     "type": "graph",
     "gridPos": { "h": 7, "w": 4, "x": 20, "y": 24 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "swift_replication_stats{hostname=~\"$swifthost\", ring=\"container\", cloud=\"$cloud\"}",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "$swifthost container replication",
     "type": "graph",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 31 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "swift_replication_stats{hostname=~\"$swifthost\", ring=\"container\", cloud=\"$cloud\"}",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "$swifthost container replication",
     "type": "graph",
     "gridPos": { "h": 7, "w": 4, "x": 4, "y": 31 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "swift_replication_stats{hostname=~\"$swifthost\", ring=\"container\", cloud=\"$cloud\"}",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "$swifthost container replication",
     "type": "graph",
     "gridPos": { "h": 7, "w": 4, "x": 8, "y": 31 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "swift_replication_stats{hostname=~\"$swifthost\", ring=\"container\", cloud=\"$cloud\"}",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "$swifthost container replication",
     "type": "graph",
     "gridPos": { "h": 7, "w": 4, "x": 12, "y": 31 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "swift_replication_stats{hostname=~\"$swifthost\", ring=\"container\", cloud=\"$cloud\"}",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "$swifthost container replication",
     "type": "graph",
     "gridPos": { "h": 7, "w": 4, "x": 16, "y": 31 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "swift_replication_stats{hostname=~\"$swifthost\", ring=\"container\", cloud=\"$cloud\"}",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "$swifthost container replication",
     "type": "graph",
     "gridPos": { "h": 7, "w": 4, "x": 20, "y": 31 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "swift_replication_stats{hostname=~\"$swifthost\", ring=\"container\", cloud=\"$cloud\"}",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "$swifthost container replication",
     "type": "graph",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 38 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "swift_replication_stats{hostname=~\"$swifthost\", ring=\"container\", cloud=\"$cloud\"}",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "$swifthost container replication",
     "type": "graph",
     "gridPos": { "h": 7, "w": 4, "x": 4, "y": 38 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "swift_replication_stats{hostname=~\"$swifthost\", ring=\"container\", cloud=\"$cloud\"}",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "$swifthost container replication",
     "type": "graph",
     "gridPos": { "h": 7, "w": 4, "x": 8, "y": 38 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "swift_replication_stats{hostname=~\"$swifthost\", ring=\"container\", cloud=\"$cloud\"}",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "$swifthost account replication",
     "type": "graph",
     "gridPos": { "h": 7, "w": 4, "x": 12, "y": 38 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "swift_replication_stats{hostname=~\"$swifthost\", ring=\"account\", cloud=\"$cloud\"}",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "$swifthost account replication",
     "type": "graph",
     "gridPos": { "h": 7, "w": 4, "x": 16, "y": 38 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "swift_replication_stats{hostname=~\"$swifthost\", ring=\"account\", cloud=\"$cloud\"}",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "$swifthost account replication",
     "type": "graph",
     "gridPos": { "h": 7, "w": 4, "x": 20, "y": 38 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "swift_replication_stats{hostname=~\"$swifthost\", ring=\"account\", cloud=\"$cloud\"}",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "$swifthost account replication",
     "type": "graph",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 45 },
     "repeat": "swifthost",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "swift_replication_stats{hostname=~\"$swifthost\", ring=\"account\", cloud=\"$cloud\"}",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "$swifthost account replication",
     "type": "graph",
     "gridPos": { "h": 7, "w": 4, "x": 4, "y": 45 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "swift_replication_stats{hostname=~\"$swifthost\", ring=\"account\", cloud=\"$cloud\"}",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "$swifthost account replication",
     "type": "graph",
     "gridPos": { "h": 7, "w": 4, "x": 8, "y": 45 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "swift_replication_stats{hostname=~\"$swifthost\", ring=\"account\", cloud=\"$cloud\"}",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "$swifthost account replication",
     "type": "graph",
     "gridPos": { "h": 7, "w": 4, "x": 12, "y": 45 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "swift_replication_stats{hostname=~\"$swifthost\", ring=\"account\", cloud=\"$cloud\"}",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "$swifthost account replication",
     "type": "graph",
     "gridPos": { "h": 7, "w": 4, "x": 16, "y": 45 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "swift_replication_stats{hostname=~\"$swifthost\", ring=\"account\", cloud=\"$cloud\"}",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "$swifthost account replication",
     "type": "graph",
     "gridPos": { "h": 7, "w": 4, "x": 20, "y": 45 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "swift_replication_stats{hostname=~\"$swifthost\", ring=\"account\", cloud=\"$cloud\"}",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "$swifthost account replication",
     "type": "graph",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 52 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "swift_replication_stats{hostname=~\"$swifthost\", ring=\"account\", cloud=\"$cloud\"}",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "$swifthost account replication",
     "type": "graph",
     "gridPos": { "h": 7, "w": 4, "x": 4, "y": 52 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "swift_replication_stats{hostname=~\"$swifthost\", ring=\"account\", cloud=\"$cloud\"}",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "$swifthost account replication",
     "type": "graph",
     "gridPos": { "h": 7, "w": 4, "x": 8, "y": 52 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "swift_replication_stats{hostname=~\"$swifthost\", ring=\"account\", cloud=\"$cloud\"}",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "$swifthost account replication",
     "type": "graph",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 59 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "swift_replication_stats{hostname=~\"$swifthost\", ring=\"account\", cloud=\"$cloud\"}",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "$swifthost account replication",
     "type": "graph",
     "gridPos": { "h": 7, "w": 4, "x": 4, "y": 59 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "swift_replication_stats{hostname=~\"$swifthost\", ring=\"account\", cloud=\"$cloud\"}",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "$swifthost account replication",
     "type": "graph",
     "gridPos": { "h": 7, "w": 4, "x": 8, "y": 59 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "swift_replication_stats{hostname=~\"$swifthost\", ring=\"account\", cloud=\"$cloud\"}",
       "legendFormat": "{{type}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Instances",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Instances in ERROR state",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "nova_instances{instance_state=\"ERROR\",cloud=\"$cloud\"}",
       "legendFormat": "{{tenant}}"
      }
     ]
    },
    {
     "title": "Top disk users",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "gbytes" }
     ],
     "targets": [
      {
       "expr": "topk(10, nova_resources_disk_gbs{cloud=\"$cloud\"})",
       "legendFormat": "{{tenant}}"
      }
     ]
    },
    {
     "title": "Top RAM users",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 18 },
     "yaxes": [
      { "format": "mbytes" }
     ],
     "targets": [
      {
       "expr": "topk(10, nova_resources_ram_mbs{cloud=\"$cloud\"})",
       "legendFormat": "{{tenant}}"
      }
     ]
    },
    {
     "title": "Top vCPU users",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "topk(10, nova_resources_vcpus{cloud=\"$cloud\"})",
       "legendFormat": "{{tenant}}"
      }
     ]
    },
    {
     "title": "Top instance owners",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 25 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "topk(10, nova_instances{cloud=\"$cloud\"})",
       "legendFormat": "{{tenant}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Openstack Exporter Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cache age",
     "type": "graph",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "openstack_exporter_cache_age_seconds{cloud=\"$cloud\"}",
       "legendFormat": "Cache age"
      }
     ]
    },
    {
     "title": "Cache refresh duration",
     "type": "graph",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "openstack_exporter_cache_refresh_duration_seconds{cloud=\"$cloud\"}",
       "legendFormat": "Refresh duration"
      }
     ]
    },
    {
     "title": "Scrape duration",
     "type": "graph",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "scrape_duration_seconds{instance=\"$instance\"}",
       "legendFormat": "Scrape duration"
      }
     ]
    }
   ]
  }
 ]
}